SELECT
    DURB.DURABLE_ID
     , DURB.DURABLE_STATUS_CODE
     , DURB.LOAD_REP_CSTID
     , DURB.CST_LOAD_LOCATION_CODE
     , DURB.RACK_ID
--      , DURB.CURR_LOTID  삭제
     , DURB.ABNORM_TRF_RSN_CODE
     , DURB.EQUIPMENT_ID
     , DURB.PORT_ID
--      , LOT.ROUTID  삭제
     , LOT.LOT_DETAIL_STATUS_CODE
     , LOT.PRODUCTION_TYPE_CODE
--      , LOT.DAY_GR_LOTID 삭제
--      , LOT.FORM_FORC_MANL_PORT 삭제
     , LOT.SPCL_FLAG
--      , LOT.SMPL_ISS_TYPE_CODE 삭제
--      , LOT.LOT_DETL_TYPE_CODE 삭제
--      , LOT.DFCT_LIMIT_OVER_FLAG  삭제
     , LOT.SPCL_NOTE
--      , LOT.FORM_SPCL_GR_ID  삭제
     , LOT.PROCESS_CODE
     , DURB.DURABLE_SPECIFICATION_ID
     , TO_CHAR(DURB.LAST_TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM
--      , LOT.DFCT_OCCR_EQPTID 삭제
--      , TO_CHAR(LOT.AGING_ISS_SCHD_DTTM, 'YYYY-MM-DD HH24:MI:SS') AS AGING_ISS_SCHD_DTTM 삭제
--      , LOT.SCRP_TRAY_FLAG  삭제
--      , LOT.TRAY_CNVR_BCR_SCAN_COUNT  삭제
FROM TB_EGN_DURB_INFO DURB
    LEFT JOIN TB_EGN_LOT_INFO LOT ON DURB.DURABLE_ID = LOT.DURABLE_ID
--          LEFT JOIN WIP W ON DURB.CURR_LOTID = W.LOTID
--          LEFT JOIN WIPATTR WA ON WA.LOTID = W.LOTID
--          LEFT JOIN LOT L ON L.LOTID = WA.LOTID
WHERE (DURB.LOAD_REP_CSTID LIKE :CSTID OR DURB.DURABLE_ID LIKE :CSTID)
ORDER BY UPDDTTM DESC, DURB.CST_LOAD_LOCATION_CODE DESC