SELECT
    REQ.REQ_SEQNO as 번호,
    REQ.CSTID AS CSTID,
    REQ.CSTSTAT as 상태,
    EA.ELTR_TYPE_CODE AS 극성,
    REQ.EQPTID AS 설비명,
    REQ.PORT_ID AS 포트명,
    REQ.REQ_TYPE_CODE AS 요청,
    REQ.RTD_RULE_ID,
    REQ.REQ_TRGT_EQPTID AS 최종EQPT,
    REQ.TRGT_EQPT_MOUNT_PSTN_ID AS UWD번호,
    TO_CHAR(REQ.INSDTTM, 'YYYY-MM-DD HH24:MI:SS'),
    TO_CHAR(REQ.UPDDTTM, 'YYYY-MM-DD HH24:MI:SS'),
    REQ.ERR_CODE,
    C.BUSINESS_USAGE_CODE_DESC,
    REQ.REQ_STAT_CODE,
    REQ.REQ_SEQS,
    REQ.PRCS_TYPE_CODE AS 코드,
    REQ.INSUSER AS 요청자,
    REQ.REQ_SEQNO,
    REQ.RTD_EXEC_LOG_CNTT
FROM TB_MHS_TRF_REQ REQ
         LEFT JOIN TB_EGN_CODE_ITEM_INFO C ON C.BUSINESS_USAGE_TYPE_CODE = 'TRF_REQ_ERR_CODE' AND C.BUSINESS_USAGE_CODE_ID = REQ.ERR_CODE
         LEFT OUTER JOIN TB_EGN_EQUIP_SPEC_MST EA ON EA.EQUIPMENT_ID = REQ.EQPTID
WHERE 1 = 1
  AND TO_CHAR(REQ.INSDTTM, 'YYYY-MM-DD') BETWEEN :StartTime AND :EndTime
  AND (REQ.CSTID IN (:CSTID) OR REQ.CSTID IN (:CSTID))   -- Option1
  AND REQ.PORT_ID LIKE :PORT_ID  -- Option2
  AND REQ.RTD_RULE_ID LIKE :RTD_RULE_ID  -- Option3
  AND REQ.REQ_STAT_CODE like :REQ_STAT_CODE  -- Option4
  AND REQ.CSTSTAT = :CSTSTAT  -- Option5
ORDER BY REQ.CSTID, REQ.UPDDTTM DESC