SELECT
    TEPI.PORT_ID,
    TEPI.TRANSFER_STATE_CODE AS 요청,
    E.EQUIPMENT_STATE_CODE AS ES,
    MAX_TRF_QTY AS 버퍼,
    E.EIOIFMODE AS EIM,
    E.EQPT_MAINT_FLAG AS MAINT_FLAG,
    TEPI.ACCESS_MODE_CODE
FROM TB_EGN_PORT_INFO TEPI
         INNER JOIN TB_EGN_EQUIP_INFO E ON E.EQUIPMENT_ID = SUBSTR(TEPI.PORT_ID, 1, 15)
         INNER JOIN TB_EGN_EQUIP_SPEC_MST EM ON E.EQUIPMENT_ID = EM.EQUIPMENT_ID
WHERE 1=1
  AND E.EQUIPMENT_ID like :EQPTID  -- option1
  AND E.EQUIPMENT_ID like :AREA_ID  -- option2
ORDER BY TEPI.PORT_ID
