SELECT
    DURABLE_ID
     , LOAD_REP_CSTID
     , TRANSACTION_CODE
     , TO_CHAR(TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ACTDTTM
     , DURABLE_STATUS_CODE
     , EQUIPMENT_ID
--    , PROCID   삭제-->
--    , LOTID    삭제
     , TRF_STAT_CODE
     , CST_LOAD_LOCATION_CODE
     , PORT_ID
     , RACK_ID
     , USE_FLAG
--     , INSUSER    삭제-->
--     , TO_CHAR(INSDTTM, 'YYYY-MM-DD HH24:MI:SS') AS INSDTTM 삭제
     , TO_CHAR(TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM
FROM TB_EGN_DURB_HIST
WHERE 1=1
  AND DURABLE_ID IN (:DURABLE_ID)  -- Option2
  AND PORT_ID LIKE :PORT_ID  -- Option3
ORDER BY ACTDTTM DESC
    FETCH FIRST :TOPNUMBER ROWS ONLY -- Option1