SELECT
    THTC.CSTID,
    THTC.CSTSTAT,
    THTC.FROM_PORT_ID,
    THTC.TO_PORT_ID,
    THTC.FINL_TRGT_EQPT_ID,
    THTC.CMD_STAT_CODE,
    DURB.LOAD_REP_CSTID,
    THTC.TRF_CODE,
    THTC.RTD_RULE_ID,
    THTC.REQ_DTTM,
    THTC.TRF_STRT_DTTM,
    THTC.UPDDTTM
FROM TB_MHS_TRF_CMD THTC
         INNER JOIN TB_EGN_DURB_INFO DURB ON DURB.DURABLE_ID = THTC.CSTID
WHERE 1 = 1
  AND (THTC.CSTID like :CSTID OR THTC.CSTID = (SELECT LOAD_REP_CSTID FROM TB_EGN_DURB_INFO WHERE DURABLE_ID like :CSTID))  -- Option1
  AND REQ_SEQNO LIKE :REQ_SEQNO  -- Option2