WITH TT_DATA AS (
    SELECT *
    FROM TB_MHS_TRF_REQ_HIST
    WHERE INSDTTM BETWEEN :StartTime AND :EndTime
      AND CSTID IN (:CSTID)  --  Option01
      AND PRCS_TYPE_CODE like :PRCS_TYPE_CODE   --  Option02
      AND PORT_ID LIKE :PORT_ID   -- Option03
    ORDER BY INSDTTM DESC
        FETCH FIRST 1000 ROWS ONLY
)
SELECT
    CSTID
     , CSTSTAT AS 상태
     , REQ_STAT_CODE
     , EQPTID
     , PORT_ID
     , REQ_TRGT_EQPTID
     , TRGT_EQPT_MOUNT_PSTN_ID AS UWD_ID
     , REQ_TYPE_CODE AS 요청
     , TO_CHAR(INSDTTM, 'YYYY-MM-DD HH24:MI:SS') AS INSDTTM
     , TO_CHAR(UPDDTTM, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM
     , PRCS_TYPE_CODE
     , RTD_RULE_ID
     , REQ_SEQS
     , ERR_CODE
     , RTD_EXEC_LOG_CNTT
     , INSUSER
     , REQ_SEQNO
FROM TT_DATA
WHERE 1=1
  AND CSTSTAT = :CSTSTAT  -- Option04
ORDER BY REQ_SEQNO DESC