SELECT
    EI.EQUIPMENT_ID,
    EI.EQUIPMENT_STATE_CODE,
    TO_CHAR(EI.EIODTTM, 'YYYY-MM-DD HH24:MI:SS') AS EIO_DTTM,
    PI.MAX_TRF_QTY,
    CE.CMD_QTY
FROM TB_EGN_EQUIP_INFO EI
         INNER JOIN TB_EGN_PORT_INFO PI ON EI.EQUIPMENT_ID = PI.PORT_ID
         LEFT JOIN (
    SELECT TO_EQPTID, TO_PORT_ID, NVL(COUNT(CSTID), 0) AS CMD_QTY
    FROM TB_MHS_TRF_CMD
    WHERE CMD_STAT_CODE IN ('RECEIVE', 'MOVING')
      AND NVL(CNCL_REQ_FLAG, '') NOT IN ('Y', 'S')
    GROUP BY TO_EQPTID, TO_PORT_ID
) CE ON EI.EQUIPMENT_ID = CE.TO_PORT_ID
WHERE EI.EQUIPMENT_ID LIKE :PORT_ID    -- option1
ORDER BY EIO_DTTM DESC
    FETCH FIRST :TOPNUMBER ROWS ONLY  -- option2
