SELECT
    CSTID
     , FROM_EQPTID
     , FROM_PORT_ID
     , TO_EQPTID
     , TO_PORT_ID
     , CSTSTAT
     , RTD_RULE_ID
     , CMD_STAT_CODE
     , INSUSER
     , TO_CHAR(MAX(INSDTTM), 'YYYY-MM-DD HH24:MI:SS') AS LASTINSDTTM
     , COUNT(CSTID) AS CNT
FROM TB_MHS_TRF_CMD_HIST
WHERE TO_CHAR(INSDTTM, 'YYYY-MM-DD') BETWEEN :StartTime AND :EndTime
  AND CMD_STAT_CODE = 'DELETE'
GROUP BY CSTID, FROM_EQPTID, FROM_PORT_ID, TO_EQPTID, TO_PORT_ID, CSTSTAT, RTD_RULE_ID, CMD_STAT_CODE, INSUSER
-- AND (EXCT_MSG LIKE :ErrText OR EXCT_TYPE LIKE :ErrText) 삭제 Option1
-- ORDER BY INSDTTM DESC
ORDER BY MAX(INSDTTM) DESC  -- option2