SELECT
    DURABLE_ID
     , LOAD_REP_CSTID
     , TRANSACTION_CODE
     , TO_CHAR(TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ACTDTTM
     , DURABLE_STATUS_CODE
     , EQUIPMENT_ID
--      , PROCID
--      , LOTID
     , TRF_STAT_CODE
     , CST_LOAD_LOCATION_CODE
     , PORT_ID
     , RACK_ID
     , USE_FLAG
--      , INSUSER
--      , TO_CHAR(INSDTTM, 'YYYY-MM-DD HH24:MI:SS') AS INSDTTM
     , TO_CHAR(TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM
FROM TB_EGN_DURB_HIST
WHERE 1=1
  AND DURABLE_ID IN (:DURABLE_ID)  -- option1
  AND PORT_ID LIKE :PORT_ID   -- option2
  AND TRANSACTION_DATE BETWEEN :StartTime AND :EndTime
ORDER BY TRANSACTION_DATE DESC