SELECT DISTINCT
    E.EQUIPMENT_ID
FROM
    TB_EGN_EQUIP_SPEC_MST E
        INNER JOIN TB_EGN_FCTRY_AREA_MST TEFAM ON E.FACTORY_AREA_ID = TEFAM.FACTORY_AREA_ID
WHERE
    TEFAM.FACILITY_CODE = :AREA_ID
  AND TEFAM.MES_SYSTEM_TYPE_CODE = :SYSTEM_TYPE_CODE
  AND E.EQUIPMENT_GROUP_ID NOT IN ('MCS')
UNION
SELECT DISTINCT
    E.EQUIPMENT_ID
FROM
    TB_EGN_EQUIP_SPEC_MST E
        INNER JOIN TB_EGN_FCTRY_AREA_MST TEFAM ON E.FACTORY_AREA_ID = TEFAM.FACTORY_AREA_ID
WHERE
    TEFAM.FACILITY_CODE = :FACILITY_CODE    -- option1
  AND E.EQUIPMENT_GROUP_ID = 'PKG';
