SELECT
    CSTID
     , CSTSTAT AS 상태
     , LOTID
     , PROCID
     , EQPTID
     , PORT_ID
     , RACK_ID
     , EVENT_CODE
     , EVENT_TYPE_CODE AS ETC
     , TRF_END_CODE AS TEC
     , FINL_TO_EQPTID AS TO_EQPT_ID
     , FINL_TO_PORT_ID AS TO_PORT_ID
     , INSUSER
     , TO_CHAR(INSDTTM, 'YYYY-MM-DD HH24:MI:SS') AS INSDTTM
     , TO_CHAR(UPDDTTM, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM
FROM TB_MHS_TRF_EVENT_HIST
WHERE 1=1
  AND CSTID IN (:CSTID)  -- Option1
  AND PORT_ID LIKE :PORT_ID  -- Option2
  AND INSDTTM BETWEEN :StartTime AND :EndTime
ORDER BY INSDTTM DESC