SELECT
    TEEI.EQUIPMENT_ID,
    TEEI.EQUIPMENT_STATE_CODE,
    TO_CHAR(TEEI.EIODTTM, 'YYYY-MM-DD HH24:MI:SS') AS EIO_DTTM,
    TEPI.MAX_TRF_QTY,
    NVL(CE.CMD_QTY, 0) AS CMD_QTY
FROM TB_EGN_EQUIP_INFO TEEI
         INNER JOIN TB_EGN_PORT_INFO TEPI ON TEEI.EQUIPMENT_ID = TEPI.PORT_ID
         LEFT JOIN (
    SELECT TO_EQPTID, TO_PORT_ID, NVL(COUNT(CSTID), 0) AS CMD_QTY
    FROM TB_MHS_TRF_CMD
    WHERE CMD_STAT_CODE IN ('RECEIVE', 'MOVING')
      AND NVL(CNCL_REQ_FLAG, '') NOT IN ('Y', 'S')
    GROUP BY TO_EQPTID, TO_PORT_ID
) CE ON TEEI.EQUIPMENT_ID = CE.TO_PORT_ID
WHERE TEEI.EQUIPMENT_ID LIKE :PORT_ID   -- option2
ORDER BY EIO_DTTM DESC
    FETCH FIRST :TOPNUMBER ROWS ONLY -- option1