SELECT
    CSTID
     , CSTSTAT AS 상태
     , LOTID
     , PROCID
     , EQPTID
     , PORT_ID
     , RACK_ID
     , EVENT_CODE
     , EVENT_TYPE_CODE
     , TRF_END_CODE
     , FINL_TO_EQPTID
     , FINL_TO_PORT_ID
     , INSUSER
     , TO_CHAR(INSDTTM, 'YYYY-MM-DD HH24:MI:SS') AS INSDTTM
     , TO_CHAR(UPDDTTM, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM
FROM TB_MHS_TRF_EVENT_HIST
WHERE 1=1
  AND CSTID IN (:CSTID)    -- option2
  AND PORT_ID LIKE :PORT_ID   --option3
ORDER BY INSDTTM DESC
    FETCH FIRST :TOPNUMBER ROWS ONLY   -- option1