select
	PORT_ID
	, PORT_STATE_CODE AS 상태
    , TRANSACTION_DATE
    , TRANSACTION_CODE
from TB_EGN_PORT_HIST
where PORT_ID like :PORT_ID  -- option1
ORDER BY TRANSACTION_DATE desc
    FETCH FIRST :TOPNUMBER ROWS ONLY  -- option2