SELECT
    PORT_ID,
    PORT_STATE_CODE AS 상태,
    TRANSACTION_DATE,
    TRANSACTION_CODE
FROM TB_EGN_PORT_HIST
WHERE PORT_ID LIKE :PORT_ID    -- option2
ORDER BY TRANSACTION_DATE DESC
FETCH FIRST :TOPNUMBER ROWS ONLY   -- option1