SELECT
    CSTID
     , LOTID
     , FROM_EQPTID
     , FROM_PORT_ID
     , TO_EQPTID
     , TO_PORT_ID
     , CSTSTAT
     , RTD_RULE_ID
     , CMD_STAT_CODE
     , INSUSER
     , TRF_CLSS_CODE AS 반송주체
     , TRF_CODE
     , TO_CHAR(INSDTTM, 'YYYY-MM-DD HH24:MI:SS') AS INSDTTM
     , TO_CHAR(UPDDTTM, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM
     , (CASE WHEN (SYSDATE - INSDTTM) * 24 * 60 >= 60 THEN '1' ELSE 'O' END) AS CMDCHK
FROM TB_MHS_TRF_CMD_HIST
WHERE INSDTTM BETWEEN :StartTime AND :EndTime
  AND CSTID IN (:CSTID)  -- Option1
  AND FROM_PORT_ID LIKE :FROM_PORT_ID  -- Option2
  AND TO_PORT_ID LIKE :TO_PORT_ID  -- Option3
  AND CSTSTAT = :CSTSTAT  -- Option4
  AND CMD_STAT_CODE = :CMD_STAT_CODE  -- Option5
  AND RTD_RULE_ID = :RTD_RULE_ID  -- Option6
ORDER BY INSDTTM DESC