WITH TT_BUF_SUM AS (
    SELECT
        TMTP.EQPTID,
        NVL(SUM(TEP.MAX_TRF_QTY), 0) AS MAX_QTY
    FROM TB_MMD_TRF_PORT TMTP
             INNER JOIN TB_EGN_PORT_INFO TEP ON TMTP.PORT_ID = TEP.PORT_ID
             INNER JOIN TB_EGN_EQUIP_SPEC_MST E ON E.EQUIPMENT_ID = TMTP.PORT_ID
             INNER JOIN TB_EGN_FCTRY_AREA_MST ES ON E.FACTORY_AREA_ID = ES.FACTORY_AREA_ID
    WHERE ES.FACILITY_CODE = :FACILITY_CODE  -- Option3
    GROUP BY TMTP.EQPTID
    HAVING NVL(SUM(TEP.MAX_TRF_QTY), 0) >= 0
),
     TT_USING_QTY AS (
         SELECT
             TO_EQPTID,
             NVL(COUNT(CSTID), 0) AS CMD_USING_QTY
         FROM TB_MHS_TRF_CMD
         WHERE CMD_STAT_CODE IN ('RECEIVE', 'MOVING')
           AND CSTSTAT = 'U'
           AND NVL(CNCL_REQ_FLAG, '') NOT IN ('Y', 'S')
         GROUP BY TO_EQPTID
     ),
     TT_EMPTY_QTY AS (
         SELECT
             TO_EQPTID,
             NVL(COUNT(CSTID), 0) AS CMD_EMPTY_QTY
         FROM TB_MHS_TRF_CMD
         WHERE CMD_STAT_CODE IN ('RECEIVE', 'MOVING')
           AND CSTSTAT = 'E'
           AND NVL(CNCL_REQ_FLAG, '') NOT IN ('Y', 'S')
         GROUP BY TO_EQPTID
     ),
     TT_TOTAL_QTY AS (
         SELECT
             TOT.EQPTID,
             TOT.MAX_QTY,
             CU.CMD_USING_QTY,
             CE.CMD_EMPTY_QTY
         FROM TT_BUF_SUM TOT
                  LEFT JOIN TT_USING_QTY CU ON TOT.EQPTID = CU.TO_EQPTID
                  LEFT JOIN TT_EMPTY_QTY CE ON TOT.EQPTID = CE.TO_EQPTID
     )
SELECT
    EQ.EQUIPMENT_ID,
    EQ.EQUIPMENT_GROUP_ID,
    EQ.USE_FLAG AS 사용,
    E.EQUIPMENT_STATE_CODE,
    E.EIOIFMODE,
    EQ.LANE_ID AS LANE_ID,
    WO.PRODUCT_SPECIFICATION_ID,
    TO_CHAR(E.LAST_TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM,
    NVL(Q.MAX_QTY, 0) AS MAX_CMD,
    NVL(Q.CMD_USING_QTY, 0) AS 실반송,
    NVL(Q.CMD_EMPTY_QTY, 0) AS 공반송
FROM TB_EGN_EQUIP_SPEC_MST EQ
         INNER JOIN TB_EGN_FCTRY_AREA_MST TEFAM ON TEFAM.FACTORY_AREA_ID = EQ.FACTORY_AREA_ID
         INNER JOIN TB_EGN_EQUIP_INFO E ON EQ.EQUIPMENT_ID = E.EQUIPMENT_ID
         LEFT JOIN TB_EGN_WO_INFO WO ON WO.WORK_ORDER_ID = E.WO_DETL_ID
         LEFT JOIN TB_SFC_FP_DETL_PLAN TSFDP ON TSFDP.WO_DETL_ID = E.WO_DETL_ID
         LEFT JOIN TB_EGN_MTL_ALT_INFO TEMAI ON E.WO_DETL_ID = TEMAI.RELATION_ID AND TEMAI.USE_FLAG = 'Y'
         LEFT JOIN TB_EGN_PROD_SPEC_MST PD ON PD.PRODUCT_SPECIFICATION_ID = TEMAI.PRIMARY_MATERIAL_SPEC_ID AND PD.USE_FLAG = 'Y'
         LEFT JOIN TT_TOTAL_QTY Q ON E.EQUIPMENT_ID = Q.EQPTID
WHERE 1 = 1
  AND TEFAM.MES_SYSTEM_TYPE_CODE = :SYSTEM_TYPE_CODE -- option2
  AND EQ.USE_FLAG = 'Y'
  AND EQ.EQUIPMENT_GROUP_ID IN (:EQP_GROUP_ID_LIST)  -- option1
  AND TEFAM.FACILITY_CODE LIKE :FACILITY_CODE
  AND EQ.EQUIPMENT_GROUP_ID IN ('CNV', 'STO', 'EOL', 'FOR', 'LAM', 'NND', 'STK')
  AND PD.PRODUCT_SPECIFICATION_ID IS NOT NULL
  AND LENGTH(EQ.EQUIPMENT_ID) = 11
UNION ALL
SELECT
    EQ.EQUIPMENT_ID,
    EQ.EQUIPMENT_GROUP_ID,
    EQ.USE_FLAG AS 사용,
    E.EQUIPMENT_STATE_CODE,
    E.EIOIFMODE,
    EQ.LANE_ID AS LANE_ID,
    WO.PRODUCT_SPECIFICATION_ID,
    TO_CHAR(E.LAST_TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM,
    NVL(Q.MAX_QTY, 0) AS MAX_CMD,
    NVL(Q.CMD_USING_QTY, 0) AS 실반송,
    NVL(Q.CMD_EMPTY_QTY, 0) AS 공반송
FROM TB_EGN_EQUIP_SPEC_MST EQ
         INNER JOIN TB_EGN_FCTRY_AREA_MST TEFAM ON TEFAM.FACTORY_AREA_ID = EQ.FACTORY_AREA_ID
         INNER JOIN TB_EGN_EQUIP_INFO E ON EQ.EQUIPMENT_ID = E.EQUIPMENT_ID
         LEFT JOIN TB_EGN_WO_INFO WO ON WO.WORK_ORDER_ID = E.WO_DETL_ID
         LEFT JOIN TB_SFC_FP_DETL_PLAN TSFDP ON TSFDP.WO_DETL_ID = E.WO_DETL_ID
         LEFT JOIN TB_EGN_MTL_ALT_INFO TEMAI ON E.WO_DETL_ID = TEMAI.RELATION_ID AND TEMAI.USE_FLAG = 'Y'
         LEFT JOIN TB_EGN_PROD_SPEC_MST PD ON PD.PRODUCT_SPECIFICATION_ID = TEMAI.PRIMARY_MATERIAL_SPEC_ID AND PD.USE_FLAG = 'Y'
         LEFT JOIN TT_TOTAL_QTY Q ON E.EQUIPMENT_ID = Q.EQPTID
WHERE 1 = 1
  AND TEFAM.MES_SYSTEM_TYPE_CODE = :SYSTEM_TYPE_CODE
  AND EQ.USE_FLAG = 'Y'
  AND EQ.EQUIPMENT_GROUP_ID IN (:EQP_GROUP_ID_LIST)
  AND TEFAM.FACILITY_CODE LIKE :FACILITY_CODE
  AND EQ.EQUIPMENT_GROUP_ID IN ('SEL', 'HPC', 'DEG', 'JGF', 'DIS', 'OCV', 'ROL', 'COT')
  AND PD.PRODUCT_SPECIFICATION_ID IS NOT NULL
  AND LENGTH(EQ.EQUIPMENT_ID) = 9
UNION ALL
SELECT
    EQ.EQUIPMENT_ID,
    EQ.EQUIPMENT_GROUP_ID,
    EQ.USE_FLAG AS 사용,
    E.EQUIPMENT_STATE_CODE,
    E.EIOIFMODE,
    EQ.LANE_ID AS LANE_ID,
    PD.PRODUCT_SPECIFICATION_ID,
    TO_CHAR(E.LAST_TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS UPDDTTM,
    NVL(Q.MAX_QTY, 0) AS MAX_CMD,
    NVL(Q.CMD_USING_QTY, 0) AS 실반송,
    NVL(Q.CMD_EMPTY_QTY, 0) AS 공반송
FROM TB_EGN_EQUIP_SPEC_MST EQ
         INNER JOIN TB_EGN_FCTRY_AREA_MST TEFAM ON TEFAM.FACTORY_AREA_ID = EQ.FACTORY_AREA_ID
         INNER JOIN TB_EGN_EQUIP_INFO E ON EQ.EQUIPMENT_ID = E.EQUIPMENT_ID
         LEFT JOIN TB_EGN_WO_INFO WO ON WO.WORK_ORDER_ID = E.WO_DETL_ID
         LEFT JOIN TB_SFC_FP_DETL_PLAN TSFDP ON TSFDP.WO_DETL_ID = E.WO_DETL_ID
         LEFT JOIN TB_EGN_MTL_ALT_INFO TEMAI ON E.WO_DETL_ID = TEMAI.RELATION_ID AND TEMAI.USE_FLAG = 'Y'
         LEFT JOIN TB_EGN_PROD_SPEC_MST PD ON PD.PRODUCT_SPECIFICATION_ID = TEMAI.PRIMARY_MATERIAL_SPEC_ID AND PD.USE_FLAG = 'Y'
         LEFT JOIN TT_TOTAL_QTY Q ON E.EQUIPMENT_ID = Q.EQPTID
WHERE 1 = 1
  AND EQ.USE_FLAG = 'Y'
  AND EQ.EQUIPMENT_GROUP_ID IN (:EQP_GROUP_ID_LIST)
  AND TEFAM.FACILITY_CODE LIKE :FACILITY_CODE
  AND EQ.EQUIPMENT_GROUP_ID IN ('PKG')
  AND LENGTH(EQ.EQUIPMENT_ID) = 11

ORDER BY EQ.EQPTID -- TODO order by 절이 작동하는지 확인 필요